{% set name = "PyQt-builder" %}
{% set version = "1.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 4515e41ae379be2e54f88a89ecf47cd6e4cac43e862c4abfde18389c2666afdf
  patches:
    - patches/0001-Use-conda-sysroot-when-building-recipes.patch
    - patches/0002-disable-test-execution-cross.patch
    - patches/0003-find-sip-distinfo.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyqt-bundle = pyqtbuild.bundle.bundle_main:main
    - pyqt-qt-wheel = pyqtbuild.bundle.qt_wheel_main:main

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6
    - sip
    - packaging
    - toml

test:
  imports:
    - pyqtbuild
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE-GPL3
  summary: The PEP 517 compliant PyQt build system
  description: |
    PyQt-builder is the PEP 517 compliant build system for PyQt and projects
    that extend PyQt. It extends the sip build system and uses Qt’s qmake to
    perform the actual compilation and installation of extension modules.

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
